### ISSUE TITLE
Angle brackets of <hr> tag are converted to html entities

### ISSUE THREAD

**Issue by sebkln** [sebkln/linebreak#3]
When the linebreak plugin is enabled, any `<hr>` tags are converted into `<p>&lt;hr/&gt;</p>`.

Thanks to Tobias Siegler for reporting this issue. I'll look into it.

**Comment by Xippo** [comment]
The problem here is this part of the plugin:
```
, CKEDITOR.on("instanceReady", function(n) {
  n.editor.dataProcessor.writer.selfClosingEnd = ">"
 })
```
if you comment this part out it will work again, but don't know if breaks anything else.

If the plugin was once loaded i experienced heavy cache issuse, so if you change the plugin code you probably don't get any result. I solved this removing the plugin loading stuff from the YAML CKEditor configuration, clearing the caches and loading the CKEditor one time (opening a content element) and then readd the loading stuff.

**Comment by sebkln** [comment]
Thanks again for your feedback. I can confirm this is the issue and will provide an updated version.

I can't say for sure why I added this in the first place. May be a fix for some early issue I encountered when initially building this plugin.
